name: ogblsc
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
  - dglteam
dependencies:
  - python=3.7.0
  - pytorch=1.6.0
  - torchvision
  - cudatoolkit=10.1
  - pip
  - scipy=1.5.2 
  - numpy=1.19.2       
  - networkx=2.5
  - scikit-learn=0.23.2
  - pandas=1.1.3
  - seaborn=0.11.0
  - matplotlib=3.3.2
  - dgl-cuda10.1
  - ipython
  - jupyter
  - jupyterlab
  - statsmodels
  - rdkit
  - pip:
      - ogb

